# Generated by Django 4.0.5 on 2024-06-02 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_medico_especialidad_alter_especialidad_especialidad'),
        ('turnera', '0003_alter_turno_especialidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.medico'),
        ),
    ]
