# Generated by Django 4.0.5 on 2024-06-01 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='medico',
            name='apellido',
            field=models.CharField(default='Sin apellido', max_length=100),
            preserve_default=False,
        ),
    ]
