# Generated by Django 4.0.5 on 2024-06-01 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_especialidad_medico_apellido'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='especialidad',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='registro.especialidad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='especialidad',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
